context:
  something: something
variants:
  - name: variant-1
    context:
      something: variant-1
  - name: variant-2
  - name: variant-3
    view: render--variant-2.twig
  - name: variant-4
    view: render--camelCaseVariant.twig
