name: release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: npm ci
    - run: npm run bootstrap
    - run: npx lerna version --conventional-commits --create-release github --yes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npx lerna publish from-git --yes --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
